image: node:lts-alpine

stages:
  - build

build:
  image: node:lts-alpine
  stage: build
  script: 
    - npm install
    - npm install -g gulp
    - gulp init
    - gulp package
  artifacts:
    paths:
      - package/*.zip