# NOTE: RENAMED FILE TO PREVENT CI/CD Kic off
# Can't find fomantic css 
stages:
  - build

build:
  image: node:lts-alpine
  stage: build
  before_script: 
    - npm ci
    - npm install -g @vue/cli
    - npm install -g gulp
  script: 
    - gulp init
    - gulp package
  artifacts:
    paths:
      - package/*.zip