stages:
  - build

build:
  image: node:latest
  services:
    - docker:dind
  stage: build
  before_script: 
    - npm ci
    - npm install -g gulp
  script: 
    - gulp init
    - npm run build:popover
  artifacts:
    paths:
      - package/*.zip