image: docker:stable
services:
  - docker:stable-dind

stages:
  - build

build:
  image: linuxbrew/debian:latest
  stage: build
  before_script:
    - brew install node@10
  script: 
    - npm install
    - npm install -g gulp
    - gulp init
    - gulp package
  artifacts:
    paths:
      - package/*.zip